### ISSUE TITLE
Error releasifying package

### ISSUE THREAD

**Issue by palbcn** [unindented/electron-installer-windows#230]
**What version of `electron-installer-windows` are you using?**
1.1.0

**What version of `node` and `npm` are you using?**
8.9.4
5.8.0

**What operating system are you using?**
Windows 7 Professional
Service Pack 1

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
I can reproduce the error with the sample electron app

> git clone https://github.com/electron/electron-quick-start
> cd electron-quick-start
> npm install
> electron-packager . --out dist
> electron-installer-windows --src dist/electron-quick-start-win32-x64/ --dest dist/installer/

**What did you expect to happen?**
succesfully build the installer

**What actually happened?**
      Error: Error releasifying package: Error executing command (Exited with status 4294967295):

the complete debug log is
[electron-installer-windows-error-log.txt](https://github.com/unindented/electron-installer-windows/files/1918899/electron-installer-windows-error-log.txt)

**Comment by fcastilloec** [comment]
Thanks for reporting again, but this is not an `electron-installer-windows` bug, it's a bug related to Squirrel.Windows. A quick google search of the error will have shown you this and workarounds (see [here](https://github.com/electron/windows-installer/issues/203)).
I want to add by saying you have 4 different workarounds (rather than the only one in the link I provided/Googled):

- Use Linux/OSX to build since this bug is not present in the `mono` implementation of Squirrel.Windows
- Change your `package.json` `name` to not use dashes. Squirrel uses dashes as the separators between the name and the version, so it's assuming `'quick'` is the version
- **Preferred**: Provide the [`name` option](https://github.com/unindented/electron-installer-windows#optionsname) via a config file to `electron-installer-windows`, i.e.: 
```json
{
  "name": "electronQuickStart"
}
```
- Don't build a `msi` installer, since the Squirrel.Windows bug is related to building a `msi`. You'll have to pass a config file with the [`noMsi` option](https://github.com/unindented/electron-installer-windows#optionsnomsi), i.e.:
```json
{
  "noMsi": true
}
```

I'll try to add a note in the README, so this is more clear.
