### ISSUE TITLE
How to add files in the install .EXE file

### ISSUE THREAD

**Issue by pickledham** [unindented/electron-installer-windows#35]
This is more of a comment than a issue. I see no other place of asking.

First, Great job in   creating this fantastic app. The app works great for me.

My question is. After running electron-packager and getting a working windows package in the 'dist' folder I added a couple more folders in there. A audio folder with sound files and a MPLAB flash utility.The electron app has no problem accessing them.  

Even tho  the two extra folders are in the 'dist' folder, electron-installer-windows is not adding them to the .exe file.  

Would it be possible to  manually add files to the SFX archive? 

**What version of `electron-installer-windows` are you using?**
     electron-installer-windows@0.2.0
**What version of `node` and `npm` are you using?**
      node@5.10.0   npm@3.9.3
**What operating system are you using?**
      Windows 10 (latest updates)
**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
       yes. also no problems compiling my own app

**Comment by martiL** [comment]
good questions. i'm also like to know how to add "external" files to .exe

**Comment by fcastilloec** [comment]
You can see this template [spec.ejs](https://github.com/unindented/electron-installer-windows/blob/master/resources/spec.ejs) which adds files to `nupkg` and hence to the `exe`.
The structure is based on what `electron-packager` creates, so if you want to add anything extra, make sure that it's under any of those folders.

I would recommend putting any extra files/folders directly on your main app root, so that `electron-packager` will also add those files/folders. This way you'll be sure that they'll be available in the `exe`. Copying files/folders to the output of `electron-packager` is a bad practice, even though electron can see them and use them.
